# 网桥 -> 方便相互通讯
networks:
  mesh-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/24"
volumes:
  mesh-es-data:
  mesh-es-logs:
services:
  # ----------------------------------------------------------------------------------------------------------------------------
  mysql:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.10
    image: mysql:8.0.32
    container_name: mesh-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    hostname: mesh-mysql
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/logs:/logs
      - ./volumes/mysql/db:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-root}
    command: [
        'mysqld',
        '--innodb-buffer-pool-size=80M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1'
      ]
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=$$MYSQL_ROOT_PASSWORD mysql -h127.0.0.1 -uroot -e \"SELECT 1\" >/dev/null"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 30
  # ----------------------------------------------------------------------------------------------------------------------------
  redis:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.15
    image: redis:7.2.4
    container_name: mesh-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    hostname: mesh-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - TZ=Asia/Shanghai
    volumes:
      - ./volumes/redis/data:/data
    command: ["sh", "-c", "exec redis-server --appendonly yes --requirepass \"$$REDIS_PASSWORD\""]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 30
  # ----------------------------------------------------------------------------------------------------------------------------
  elasticsearch:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.20
    build:
      context: ./elasticsearch
    image: mesh-elasticsearch:9.5.1-icu
    container_name: mesh-elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - mesh-es-data:/usr/share/elasticsearch/data
      - mesh-es-logs:/usr/share/elasticsearch/logs
    environment:
      - cluster.name=mesh-elasticsearch
      - node.name=mesh-elasticsearch
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0         # 关键设置：绑定到所有网络接口
      - http.host=0.0.0.0            # HTTP服务绑定
      - transport.host=0.0.0.0        # 内部通信绑定
      #      - ELASTIC_PASSWORD=YourSecurePassword123!
      - xpack.security.enabled=false  # 禁用安全认证
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
  # ----------------------------------------------------------------------------------------------------------------------------
  nacos:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.25
    image: nacos/nacos-server:v2.3.2
    container_name: nacos
    restart: unless-stopped
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
      - "9555:9555"
    hostname: mesh-nacos
    volumes:
      - ./volumes/nacos/data:/home/nacos/data
      - ./volumes/nacos/logs:/home/nacos/logs
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
      - TZ=Asia/Shanghai
      - JVM_XMS=256m
      - JVM_XMX=384m
      - JVM_XMN=128m
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8848/nacos/v1/console/health/readiness >/dev/null"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 30
  # ----------------------------------------------------------------------------------------------------------------------------
  xxl-job:
    # 未提供 xxl_job 初始化 SQL，默认不启动；准备好数据库后可单独启用。
    profiles: [jobs]
    networks:
      mesh-network:
        ipv4_address: 172.22.0.29
    image: xuxueli/xxl-job-admin:3.0.0
    container_name: xxl-job
    restart: unless-stopped                                      # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    environment:
      # TODO 根据自己的配置修改，配置项参考源码文件：/xxl-job/xxl-job-admin/src/main/resources/application.properties
      PARAMS: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
               --spring.datasource.username=root
               --spring.datasource.password=root
               --server.servlet.context-path=/xxl-job-admin
               --xxl.job.accessToken=123456"
    ports:
      - "9003:8080"
    depends_on:
      mysql:
        condition: service_healthy
  # ----------------------------------------------------------------------------------------------------------------------------
  nginx-ui:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.30
    container_name: mesh-ui
    restart: always
    image: nginx:1.27-alpine
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
    volumes:
      - ../../web:/usr/share/nginx/html:ro
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./volumes/nginx/logs:/var/log/nginx
    depends_on:
      mesh-gateway:
        condition: service_healthy
  # ----------------------------------------------------------------------------------------------------------------------------
  mesh-gateway:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.35
    container_name: mesh-gateway
    image: mesh-gateway
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CLOUD_NACOS_CONFIG_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=pro
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=pro
      - MESH_DATABASE_URL=mysql:3306
      - MESH_DATABASE_PASSWORD=${MYSQL_PASSWORD:-root}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - MESH_ENVIRONMENT_ADDR_MESHSERVERADDR=mesh-gateway
      - MESH_ENVIRONMENT_ADDR_DBSERVERADDR=mysql:3306
      - MESH_ENVIRONMENT_ADDR_RDSERVERADDR=redis
      - MESH_ENVIRONMENT_ADDR_ESSERVERADDR=elasticsearch:9200
      - MESH_DATA_TENANT_ENABLE=false
      - MESH_JOB_XXL_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_ACCESS=unrestricted
    build:
      context: ../..
      dockerfile: script/docker/server/Dockerfile
      args:
        APP_NAME: "mesh-gateway"
        APP_PORT: "8080"
        JAVA_OPTS: "-XX:+UseG1GC -Xms128m -Xmx640m"
    ports:
      - "8080:8080"
    depends_on:
      nacos:
        condition: service_healthy
      redis:
        condition: service_healthy
  mesh-uaa:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.36
    container_name: mesh-uaa
    image: mesh-uaa
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CLOUD_NACOS_CONFIG_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=pro
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=pro
      - MESH_DATABASE_URL=mysql:3306
      - MESH_DATABASE_PASSWORD=${MYSQL_PASSWORD:-root}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - MESH_ENVIRONMENT_ADDR_MESHSERVERADDR=mesh-gateway
      - MESH_ENVIRONMENT_ADDR_DBSERVERADDR=mysql:3306
      - MESH_ENVIRONMENT_ADDR_RDSERVERADDR=redis
      - MESH_ENVIRONMENT_ADDR_ESSERVERADDR=elasticsearch:9200
      - MESH_DATA_TENANT_ENABLE=false
      - MESH_JOB_XXL_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_ACCESS=unrestricted
    build:
      context: ../..
      dockerfile: script/docker/server/Dockerfile
      args:
        APP_NAME: "mesh-uaa"
        APP_PORT: "8081"
        JAVA_OPTS: "-XX:+UseG1GC -Xms128m -Xmx640m"
    ports:
      - "8081:8081"
    depends_on:
      nacos:
        condition: service_healthy
      redis:
        condition: service_healthy
  mesh-upms:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.37
    container_name: mesh-upms
    image: mesh-upms
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CLOUD_NACOS_CONFIG_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=pro
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=pro
      - MESH_DATABASE_URL=mysql:3306
      - MESH_DATABASE_PASSWORD=${MYSQL_PASSWORD:-root}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - MESH_ENVIRONMENT_ADDR_MESHSERVERADDR=mesh-gateway
      - MESH_ENVIRONMENT_ADDR_DBSERVERADDR=mysql:3306
      - MESH_ENVIRONMENT_ADDR_RDSERVERADDR=redis
      - MESH_ENVIRONMENT_ADDR_ESSERVERADDR=elasticsearch:9200
      - MESH_DATA_TENANT_ENABLE=false
      - MESH_JOB_XXL_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_ACCESS=unrestricted
    build:
      context: ../..
      dockerfile: script/docker/server/Dockerfile
      args:
        APP_NAME: "mesh-upms"
        APP_PORT: "8082"
        JAVA_OPTS: "-XX:+UseG1GC -Xms128m -Xmx640m"
    ports:
      - "8082:8082"
    depends_on:
      nacos:
        condition: service_healthy
      redis:
        condition: service_healthy
  mesh-bpm:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.38
    container_name: mesh-bpm
    image: mesh-bpm
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CLOUD_NACOS_CONFIG_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=pro
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=pro
      - MESH_DATABASE_URL=mysql:3306
      - MESH_DATABASE_PASSWORD=${MYSQL_PASSWORD:-root}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - MESH_ENVIRONMENT_ADDR_MESHSERVERADDR=mesh-gateway
      - MESH_ENVIRONMENT_ADDR_DBSERVERADDR=mysql:3306
      - MESH_ENVIRONMENT_ADDR_RDSERVERADDR=redis
      - MESH_ENVIRONMENT_ADDR_ESSERVERADDR=elasticsearch:9200
      - MESH_DATA_TENANT_ENABLE=false
      - MESH_JOB_XXL_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_ACCESS=unrestricted
    build:
      context: ../..
      dockerfile: script/docker/server/Dockerfile
      args:
        APP_NAME: "mesh-bpm"
        APP_PORT: "8084"
        JAVA_OPTS: "-XX:+UseG1GC -Xms128m -Xmx640m"
    ports:
      - "8084:8084"
    depends_on:
      nacos:
        condition: service_healthy
      redis:
        condition: service_healthy
  mesh-app:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.39
    container_name: mesh-app
    image: mesh-app
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CLOUD_NACOS_CONFIG_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=pro
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=pro
      - MESH_DATABASE_URL=mysql:3306
      - MESH_DATABASE_PASSWORD=${MYSQL_PASSWORD:-root}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - MESH_ENVIRONMENT_ADDR_MESHSERVERADDR=mesh-gateway
      - MESH_ENVIRONMENT_ADDR_DBSERVERADDR=mysql:3306
      - MESH_ENVIRONMENT_ADDR_RDSERVERADDR=redis
      - MESH_ENVIRONMENT_ADDR_ESSERVERADDR=elasticsearch:9200
      - MESH_DATA_TENANT_ENABLE=false
      - MESH_JOB_XXL_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_ACCESS=unrestricted
    build:
      context: ../..
      dockerfile: script/docker/server/Dockerfile
      args:
        APP_NAME: "mesh-app"
        APP_PORT: "8085"
        JAVA_OPTS: "-XX:+UseG1GC -Xms128m -Xmx640m"
    ports:
      - "8085:8085"
    depends_on:
      nacos:
        condition: service_healthy
      redis:
        condition: service_healthy
  mesh-crm:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.40
    container_name: mesh-crm
    image: mesh-crm
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CLOUD_NACOS_CONFIG_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=pro
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=pro
      - MESH_DATABASE_URL=mysql:3306
      - MESH_DATABASE_PASSWORD=${MYSQL_PASSWORD:-root}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - MESH_ENVIRONMENT_ADDR_MESHSERVERADDR=mesh-gateway
      - MESH_ENVIRONMENT_ADDR_DBSERVERADDR=mysql:3306
      - MESH_ENVIRONMENT_ADDR_RDSERVERADDR=redis
      - MESH_ENVIRONMENT_ADDR_ESSERVERADDR=elasticsearch:9200
      - MESH_DATA_TENANT_ENABLE=false
      - MESH_JOB_XXL_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_ACCESS=unrestricted
    build:
      context: ../..
      dockerfile: script/docker/server/Dockerfile
      args:
        APP_NAME: "mesh-crm"
        APP_PORT: "8090"
        JAVA_OPTS: "-XX:+UseG1GC -Xms128m -Xmx640m"
    ports:
      - "8090:8090"
    depends_on:
      mesh-app:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      nacos:
        condition: service_healthy
      redis:
        condition: service_healthy
  mesh-ai:
    networks:
      mesh-network:
        ipv4_address: 172.22.0.41
    container_name: mesh-ai
    image: mesh-ai
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CLOUD_NACOS_CONFIG_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=pro
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=pro
      - MESH_DATABASE_URL=mysql:3306
      - MESH_DATABASE_PASSWORD=${MYSQL_PASSWORD:-root}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - MESH_ENVIRONMENT_ADDR_MESHSERVERADDR=mesh-gateway
      - MESH_ENVIRONMENT_ADDR_DBSERVERADDR=mysql:3306
      - MESH_ENVIRONMENT_ADDR_RDSERVERADDR=redis
      - MESH_ENVIRONMENT_ADDR_ESSERVERADDR=elasticsearch:9200
      - MESH_DATA_TENANT_ENABLE=false
      - MESH_JOB_XXL_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_ACCESS=unrestricted
    build:
      context: ../..
      dockerfile: script/docker/server/Dockerfile
      args:
        APP_NAME: "mesh-ai"
        APP_PORT: "8092"
        JAVA_OPTS: "-XX:+UseG1GC -Xms128m -Xmx640m"
    ports:
      - "8092:8092"
    depends_on:
      nacos:
        condition: service_healthy
      redis:
        condition: service_healthy
