<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.platform</groupId>
        <artifactId>mesh-app</artifactId>
        <version>3.5.0</version>
    </parent>

    <artifactId>mesh-app-api</artifactId>
    <version>3.5.0</version>
    <description>应用管理API</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencies>

        <!--feign-->
        <dependency>
            <groupId>com.platform</groupId>
            <artifactId>start-rpc-feign</artifactId>
        </dependency>
        <!--Swagger-->
        <dependency>
            <groupId>com.platform</groupId>
            <artifactId>start-swagger</artifactId>
        </dependency>
        <!-- search -->
        <dependency>
            <groupId>com.platform</groupId>
            <artifactId>start-search</artifactId>
        </dependency>
    </dependencies>

</project>