<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.platform</groupId>
        <artifactId>start-msg</artifactId>
        <version>4.1.0</version>
    </parent>

    <artifactId>start-msg-sms</artifactId>
    <version>4.1.0</version>

    <properties>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!--工具集-->
        <dependency>
            <groupId>com.platform</groupId>
            <artifactId>start-utils</artifactId>
        </dependency>
        <!--redis缓存-->
        <dependency>
            <groupId>com.platform</groupId>
            <artifactId>start-redis</artifactId>
        </dependency>
        <!--短信处理发送框架-->
        <dependency>
            <groupId>org.dromara.sms4j</groupId>
            <artifactId>sms4j-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

</project>