server {
    listen       80;
    server_name  49.235.98.136 woscosmos.com;

    location / {
        root   /opt/ui/home;
        try_files $uri $uri/ /index.html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

