map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    server_name  ws.example.com;

    # API接口转发
    location /ws {
	proxy_pass http://127.0.0.1:8093/ws;
	# WebSocket 必需的头信息
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        # 通用请求头
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

	    #add_header 'Access-Control-Allow-Origin' '$http_origin' always;
	    # 匹配全部懒人模式
	    add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        # WebSocket必须包含Upgrade和Connection
        #add_header 'Access-Control-Allow-Headers' 'Upgrade, Connection, Content-Type' always;
        # 匹配全部懒人模式
        add_header 'Access-Control-Allow-Headers' '*' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;

        # 长连接设置
        proxy_read_timeout 86400s;  # 24小时，适合长连接
        proxy_send_timeout 8640s;
        proxy_connect_timeout 30s;
        # 禁用缓冲（WebSocket是实时流，必须关闭缓冲）
        proxy_buffering off;
        # 额外添加：禁用缓存
        proxy_cache off;

        # 处理OPTIONS预检请求（WebSocket握手前可能发送）
        if ($request_method = 'OPTIONS') {
            return 204;  # 直接返回成功，无需内容
        }
    }

    listen 80;
}
