<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>supports</artifactId>
        <groupId>com.platform</groupId>
        <version>4.1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>mesh-gateway</artifactId>
    <version>4.1.0</version>
    <description>Gateway网关</description>


    <dependencies>
        <dependency>
            <groupId>com.platform</groupId>
            <artifactId>start-cloud</artifactId>
        </dependency>

        <dependency>
            <groupId>com.platform</groupId>
            <artifactId>start-rpc-feign</artifactId>
        </dependency>

        <!--gateway 网关依赖,内置webflux 依赖-->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway-server-webflux</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Sentinel Gateway -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
        </dependency>

        <!-- Sentinel Datasource Nacos -->
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
        </dependency>

        <!-- knife4接口文档 -->
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-gateway-spring-boot-starter</artifactId>
        </dependency>

        <!--Redis缓存-->
        <dependency>
            <groupId>com.platform</groupId>
            <artifactId>start-redis</artifactId>
        </dependency>

    </dependencies>

    <!-- 需要以服务方式运行的包，按照以下进行build plugin的配置，以便支持docker打包；-->
    <!-- 而仅作为依赖的工具型代码包，类似于start-core之类的包，则不需要这样配置，甚至不需要<build>部分内容 -->
    <!-- 如果当前包中包含，例如：字体、证书等资源，需要配置maven-resources-plugin，以防止重要静态资源文件被spring boot重新编码 -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
<!--            <plugin>-->
<!--                <groupId>io.fabric8</groupId>-->
<!--                <artifactId>docker-maven-plugin</artifactId>-->
<!--            </plugin>-->
        </plugins>
    </build>

</project>
